import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import { authenticatedRequest } from '../client/http'
import { getTokenFromStorage } from '../client/localStorage'
import {
  apiRouteFile,
  apiRouteFileShare,
  apiRouteFileUpload,
} from '../client/routes'
import File from '../components/File/File'
import FileToggle from '../components/File/FileToggle'
import Header from '../components/Header/Header'
import AddFilesDialog from '../components/Partials/AddFilesDialog'
import FileActions from '../components/Partials/FileActions'
import ShareFilesDialog from '../components/Partials/ShareFilesDialog'
import { getUserFiles, getUserFilesIfNotExists } from '../store/filesStore'
import { getMe } from '../store/meStore'
import snackStore from '../store/snackStore'
import { useAppDispatch, useAppSelector } from '../store/store'
import { getUsersIfNotExists, TFilePermission } from '../store/userStore'

type HomeState = {
  selectedFileIds: string[]
  isAddingFiles: boolean
  isSharingFiles: boolean
  fileToggle: number
}

export default function Home() {
  const dispatch = useAppDispatch()
  const { files, me } = useAppSelector((state) => ({
    files: state.files,
    me: state.me,
  }))
  const [state, setState] = useState<HomeState>({
    selectedFileIds: [],
    isAddingFiles: false,
    isSharingFiles: false,
    fileToggle: 1,
  })

  const request = authenticatedRequest(getTokenFromStorage())

  const filesToRender = files.data.filter((file) => {
    if (state.fileToggle === 2) return file.owner === me.id
    else if (state.fileToggle === 3) return file.userPermission[me.id]?.read
    return true
  })

  useEffect(() => {
    dispatch(getUserFilesIfNotExists)
    dispatch(getMe)
    dispatch(getUsersIfNotExists)
  }, [])

  const onCloseAddingFiles = () => setState({ ...state, isAddingFiles: false })
  const onOpenAddingFiles = () => setState({ ...state, isAddingFiles: true })

  const onOpenSharing = () => setState({ ...state, isSharingFiles: true })
  const onCloseSharingFiles = () =>
    setState({ ...state, isSharingFiles: false })

  const onSetFileToggle = (fileToggleId) =>
    setState({ ...state, fileToggle: fileToggleId, selectedFileIds: [] })

  const onSelectFile = (id: string) => {
    const isSelected = state.selectedFileIds.includes(id)
    if (isSelected) {
      const selectedFileIds = state.selectedFileIds.filter(
        (selectedFile) => selectedFile !== id
      )

      setState({
        ...state,
        selectedFileIds,
      })
    } else {
      setState({ ...state, selectedFileIds: state.selectedFileIds.concat(id) })
    }
  }

  const onDelete = async () => {
    const selectedFileIdParams = state.selectedFileIds.reduce(
      (acc, next) => acc + '&id=' + next,
      ''
    )
    try {
      await request.delete(`${apiRouteFile}?${selectedFileIdParams}`)
    } catch (error) {
      dispatch(snackStore.actions.showSnack(error))
    }

    dispatch(
      snackStore.actions.showSnack(
        `${state.selectedFileIds.length} files deleted.`
      )
    )
    setState({ ...state, selectedFileIds: [] })
    dispatch(getUserFiles)
  }

  const onShare = async (permission: TFilePermission) => {
    const body = { fileIds: state.selectedFileIds, permission }

    try {
      await request.put(apiRouteFileShare, JSON.stringify(body))
    } catch (error) {
      dispatch(snackStore.actions.showSnack(error))
    }

    dispatch(
      snackStore.actions.showSnack(
        `${state.selectedFileIds.length} files shared!`
      )
    )
    setState({ ...state, isSharingFiles: false, selectedFileIds: [] })
    dispatch(getUserFiles)
  }

  const onUpload = async (files: File[]) => {
    const formData = new FormData()
    files.forEach((file) => formData.append(file.name, file))

    try {
      await request.post(apiRouteFileUpload, formData)
    } catch (error) {
      dispatch(snackStore.actions.showSnack(error))
    }

    dispatch(snackStore.actions.showSnack(`${files.length} files uploaded!`))
    setState({ ...state, isAddingFiles: false })
    dispatch(getUserFiles)
  }

  return (
    <>
      <Head>
        <title>MyDrive</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header>
          <>
            <p className="header__upload" onClick={onOpenAddingFiles}>
              Upload files
            </p>
            <div className="header__avatar avatar">
              {me.name.substring(0, 1)}
            </div>
          </>
        </Header>
        <main className="main">
          <div className={'container'}>
            <h1 className="m-b-2">Files</h1>
            <div className="file-toggles">
              <FileToggle
                id={1}
                text="All files"
                onClick={onSetFileToggle}
                isSelected={state.fileToggle === 1}
              />
              <FileToggle
                id={2}
                text="My files"
                onClick={onSetFileToggle}
                isSelected={state.fileToggle === 2}
              />
              <FileToggle
                id={3}
                text="Shared with me"
                onClick={onSetFileToggle}
                isSelected={state.fileToggle === 3}
              />
            </div>
            <FileActions
              onDelete={onDelete}
              onOpenSharing={onOpenSharing}
              selectedFileIds={state.selectedFileIds}
              files={files}
              me={me}
            />
            <div className="row">
              {filesToRender.map((file) => (
                <File
                  key={file.id}
                  file={file}
                  me={me}
                  onClick={() => onSelectFile(file.id)}
                  isSelected={Boolean(
                    state.selectedFileIds.find((id) => id === file.id)
                  )}
                />
              ))}
            </div>
          </div>
        </main>
        <AddFilesDialog
          isOpen={state.isAddingFiles}
          onClose={onCloseAddingFiles}
          onUpload={onUpload}
        />
        <ShareFilesDialog
          isOpen={state.isSharingFiles}
          onClose={onCloseSharingFiles}
          onShare={onShare}
          fileNames={state.selectedFileIds}
        />
      </div>
    </>
  )
}
