import Head from 'next/head'
import { useAppSelector } from '../store/store'

export default function Home() {
  const files = useAppSelector((state) => state.files)
  return (
    <>
      <Head>
        <title>MyDrive</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={''}>
        <h1>Home</h1>

        <h2>Files</h2>
        <div>
          {files.data.map((file) => (
            <p key={file.id}>{file.name}</p>
          ))}
        </div>
      </main>
    </>
  )
}
